contact_links:
  - name: 📚 Documentation
    url: https://digimarket.savyjs.com/
    about: Check documentation for usage
  - name: 💬 Discussions
    url: https://github.com/savyjs/nuxt-digimarket-kit/discussions
    about: Use discussions if you have an idea for improvement and asking questions
