on:
  push:
    tags: v*.*.*

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish tag to npm
        if: contains(github.ref, 'tags')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

